export { User } from './User.ts'
export type { IUser } from './User.ts'
export { Patient } from './Patient.ts'
export type { IPatient } from './Patient.ts'
export { Clinic } from './Clinic.ts'
export type { IClinic } from './Clinic.ts'
export { Doctor } from './Doctor.ts'
export type { IDoctor } from './Doctor.ts'
export { Lab } from './Lab.ts'
export type { ILab } from './Lab.ts'
export { Visit } from './Visit.ts'
export type { IVisit } from './Visit.ts'
export { LabOrder } from './LabOrder.ts'
export type { ILabOrder, LabOrderStatus } from './LabOrder.ts'
export { Consent } from './Consent.ts'
export type { IConsent } from './Consent.ts'
export { AccessLog } from './AccessLog.ts'
export type { IAccessLog } from './AccessLog.ts'
export { Prescription } from './Prescription.ts'
export type { IPrescription } from './Prescription.ts'
export { LabReport } from './LabReport.ts'
export type { ILabReport } from './LabReport.ts'
export { RefDrug } from './RefDrug.ts'
export type { IRefDrug } from './RefDrug.ts'
export { RefInteraction } from './RefInteraction.ts'
export type { IRefInteraction } from './RefInteraction.ts'
export { ConsentRequest } from './ConsentRequest.ts'
export type { IConsentRequest } from './ConsentRequest.ts'
